{% set name = "lalinference" %}
{% set version = "2.0.0" %}
{% set sha256 = "0f6527590e5e72dc6dbaeff5a8bd36bf1c477c59ae80c776b0b1392018cb095e" %}

# dependencies
{% set lal_version = "6.21.0" %}
{% set lalburst_version = "1.5.3" %}
{% set lalframe_version = "1.5.0" %}
{% set lalinspiral_version = "1.10.0" %}
{% set lalmetaio_version = "1.6.0" %}
{% set lalpulsar_version = "1.18.2" %}
{% set lalsimulation_version = "2.0.0" %}
{% set swig_version = "3.0.9" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz"
  sha256: "{{ sha256 }}"

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - lal >={{ lal_version }} fftw*
    - lalframe >={{ lalframe_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - lalburst >={{ lalburst_version }}
    - lalinspiral >={{ lalinspiral_version }}
    - lalpulsar >={{ lalpulsar_version }}
    - libcblas
    - openmpi
  run:
    - gsl
    - lal >={{ lal_version }}
    - lalframe >={{ lalframe_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - lalburst >={{ lalburst_version }}
    - lalinspiral >={{ lalinspiral_version }}
    - lalpulsar >={{ lalpulsar_version }}
    - libcblas
    - openmpi

test:
  requires:
    - openssh
    - pkg-config  # [unix]
  commands:
    - test -f "${LALINFERENCE_DATADIR}/lalinference_pipe_example.ini"  # [unix]
    - lalinference_bench --psdlength 1000 --psdstart 1 --seglen 8 --srate 4096 --trigtime 0 --ifo H1 --H1-channel LALSimAdLIGO --H1-cache LALSimAdLIGO --dataseed 1324 --Niter 10 --fix-chirpmass 1.21
    #- lalinference_burst --help
    - lalinference_datadump --help
    - lalinference_injectedlike --help
    - lalinference_kombine --help
    - lalinference_mcmc --help
    - lalinference_nest --help
    - lalinference_version --verbose
    - test "$(pkg-config --modversion ${PKG_NAME})" == "${PKG_VERSION}"  # [unix]

outputs:
  - name: lalinference
    build:
      run_exports:
        - {{ pin_subpackage("lalinference", max_pin="x") }}

  - name: python-lalinference
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - libcblas  # [not linux]
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
      host:
        - gsl
        - {{ pin_subpackage('lalinference', exact=True) }}
        - libcblas
        - numpy
        - python
        # run requirements needed for help2man
        - astropy >=1.1.1
        - healpy >=1.9.1
        - h5py
        - lscsoft-glue >=1.54.1
        - matplotlib-base >=1.2.0
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-lalburst >={{ lalburst_version }}
        - python-lalinspiral >={{ lalinspiral_version }}
        - python-lalpulsar >={{ lalpulsar_version }}
        - scipy >=0.9.0
      run:
        - astropy >=1.1.1
        - gsl
        - healpy >=1.9.1
        - h5py
        - lal >={{ lal_version }}
        - lalframe >={{ lalframe_version }}  # [linux]
        - lalmetaio >={{ lalmetaio_version }}  # [linux]
        - lalsimulation >={{ lalsimulation_version }}  # [linux]
        - lalburst >={{ lalburst_version }}  # [linux]
        - lalinspiral >={{ lalinspiral_version }}  # [linux]
        - lalpulsar >={{ lalpulsar_version }}  # [linux]
        - {{ pin_subpackage('lalinference', exact=True) }}
        - libcblas  # [linux]
        - lscsoft-glue >=1.54.1
        - matplotlib-base >=1.2.0
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-lalburst >={{ lalburst_version }}
        - python-lalinspiral >={{ lalinspiral_version }}
        - python-lalpulsar >={{ lalpulsar_version }}
        - scipy >=0.9.0
    test:
      imports:
        - lalinference
        - lalinference.distance
        - lalinference.imrtgr
        - lalinference.imrtgr.imrtgrutils
        - lalinference.imrtgr.nrutils
        - lalinference.imrtgr.pneqns
        - lalinference.moc
        - lalinference.nest2pos
        - lalinference.tiger
        - lalinference.tiger.make_injtimes
        - lalinference.tiger.omegascans_dag
        - lalinference.tiger.postproc
      requires:
        - cpnest
        - mock  # [py<33]
        - pathlib  # [py<34]
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - cbcBayesBurstPPAnalysis --help
        - cbcBayesBurstPostProc --help
        - cbcBayesCombinePTMCMCh5s --help
        - cbcBayesCombinePosteriors --help
        - cbcBayesCompPos --help
        - cbcBayesDIEvidence --help
        - cbcBayesGraceDBinfo --help
        - cbcBayesMCMC2pos --help
        - cbcBayesPPAnalysis --help
        - cbcBayesPlotSpinDisk --help
        - cbcBayesPosToSimBurst --help
        - cbcBayesPosToSimInspiral --help
        - cbcBayesPostProc --help
        - cbcBayesThermoInt --help
        - imrtgr_imr_consistency_test --help
        - lalinference_burst_pp_pipe --help
        - lalinference_coherence_test --help
        - lalinference_compute_roq_weights --help
        - lalinference_cpnest --help
        - lalinference_merge_posteriors --help
        - lalinference_multi_pipe --help
        - lalinference_nest2pos --help
        - lalinference_pipe --help
        - lalinference_pp_pipe --help
        - lalinference_review_test --help
        - pushd test/python; python -m pytest -rs -v; popd
    about:
      home: "https://wiki.ligo.org/Computing/LALSuite"
      doc_url: "https://docs.ligo.org/lscsoft/lalsuite/lalinference/"
      dev_url: "https://git.ligo.org/lscsoft/lalsuite/"
      license: "GPL-2.0-or-later"
      license_family: "GPL"
      license_file: "COPYING"
      summary: "LSC Algorithm Inference Library"
      description: |
        The LSC Algorithm Inference Library for gravitational wave data
        analysis.  This package contains the python bindings.

about:
  home: "https://wiki.ligo.org/Computing/LALSuite"
  doc_url: "https://docs.ligo.org/lscsoft/lalsuite/lalinference/"
  dev_url: "https://git.ligo.org/lscsoft/lalsuite/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "LSC Algorithm Inference Library"
  description: |
    The LSC Algorithm Inference Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL Inference library.  If you want to install
    the Python bindings, please install the associated python-lalinference
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
    - vivienr
