{% set name = "lalinference" %}
{% set version = "1.10.2" %}
{% set sha256 = "bc16224ba96f278f0e7c4a2b88d5e8afc6a54cd2eac87c0384ad45dde7dfbee1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # fix python3 syntax
    - lalinference-python3.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - swig >=3.0.7
  host:
    - gsl
    - metaio
    - chealpix >=3.30.0
    - lal >=6.19.0
    - lalmetaio >=1.4.0
    - lalsimulation >=1.8.0
    - lalburst >=1.5.0
    - lalinspiral >=1.8.0
    - lalpulsar >=1.17.0

outputs:
  - name: lalinference
    script: install-c.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - make
        - swig >=3.0.7
      host:
        - gsl
        - metaio
        - chealpix >=3.30.0
        - lal >=6.19.0
        - lalmetaio >=1.4.0
        - lalsimulation >=1.8.0
        - lalburst >=1.5.0
        - lalinspiral >=1.8.0
        - lalpulsar >=1.17.0
      run:
        - gsl
        - metaio
        - chealpix >=3.30.0
        - lal >=6.19.0
        - lalmetaio >=1.4.0
        - lalsimulation >=1.8.0
        - lalburst >=1.5.0
        - lalinspiral >=1.8.0
        - lalpulsar >=1.17.0
    test:
      commands:
        - lalinference_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalinference/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inference Library
      description: |
        The LSC Algorithm Inference Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Inference library.

  - name: python-lalinference
    script: install-python.sh
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >=3.0.7
      host:
        - {{ pin_subpackage('lalinference', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lalinference', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - python-lal >=6.19.0
        - python-lalmetaio >=1.4.0
        - python-lalsimulation >=1.8.0
        - python-lalburst >=1.5.0
        - python-lalinspiral >=1.8.0
        - python-lalpulsar >=1.17.0
        - scipy >=0.8
        - lscsoft-glue >=1.54.1
        - healpy >=1.9.1
        - astropy >=1.1.1
        - matplotlib >=1.2.0
        - h5py
        - shapely
    test:
      imports:
        - lalinference
        - lalinference.imrtgr
        - lalinference.imrtgr.imrtgrutils
        - lalinference.imrtgr.nrutils
        - lalinference.imrtgr.pneqns
        - lalinference.nest2pos
        - lalinference.rapid_pe
        - lalinference.rapid_pe.common_cl
        - lalinference.rapid_pe.dagutils
        - lalinference.rapid_pe.mcsampler
        - lalinference.rapid_pe.statutils
        - lalinference.rapid_pe.synchlib
        - lalinference.rapid_pe.xmlutils
        - lalinference.tiger
        - lalinference.tiger.make_injtimes
        - lalinference.tiger.omegascans_dag
        - lalinference.tiger.postproc
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalinference/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inference Library
      description: |
        The LSC Algorithm Inference Library for gravitational wave data
        analysis.  This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm Inference Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
    - vivienr
