{% set name = "lalinference" %}
{% set version = "2.0.6" %}
{% set sha256 = "b58195713edf23da074e9f08cc9a767d5d5e11d6d94f4771618ff6a70dc278c0" %}
{% set build = 0 %}

# dependencies
{% set lal_version = "7.1.0" %}
{% set lalburst_version = "1.5.3" %}
{% set lalframe_version = "1.5.0" %}
{% set lalinspiral_version = "2.0.0" %}
{% set lalmetaio_version = "2.0.0" %}
{% set lalpulsar_version = "3.0.0" %}
{% set lalsimulation_version = "2.5.0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - llvm-openmp  # [osx]
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - lal >={{ lal_version }} fftw*
    - lalframe >={{ lalframe_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - lalburst >={{ lalburst_version }}
    - lalinspiral >={{ lalinspiral_version }}
    - lalpulsar >={{ lalpulsar_version }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

outputs:
  - name: liblalinference
    script: install-lib.sh
    build:
      error_overdepending: true
      error_overlinking: true
      run_exports:
        - {{ pin_subpackage("liblalinference", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - llvm-openmp  # [osx]
        - make
        - swig >={{ swig_version }}
      host:
        - gsl
        - libgomp  # [linux]
        - liblal >={{ lal_version }} fftw*
        - liblalframe >={{ lalframe_version }}
        - liblalmetaio >={{ lalmetaio_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - liblalburst >={{ lalburst_version }}
        - liblalinspiral >={{ lalinspiral_version }}
        - liblalpulsar >={{ lalpulsar_version }}
        - llvm-openmp  # [osx]
      run:
        - gsl
        - liblal >={{ lal_version }} fftw*
        - liblalframe >={{ lalframe_version }}
        - liblalmetaio >={{ lalmetaio_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - liblalburst >={{ lalburst_version }}
        - liblalinspiral >={{ lalinspiral_version }}
        - liblalpulsar >={{ lalpulsar_version }}
        - llvm-openmp  # [osx]
    test:
      requires:
        - pkg-config
      commands:
        - test $(pkg-config --modversion --print-errors lalinference) == "${PKG_VERSION}"

  - name: python-lalinference
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - openmpi
        # ignore run_exports from python's recipe
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('liblalinference', exact=True) }}
        - python
        - numpy
        # run requirements needed for help2man
        - astropy >=1.1.1
        - healpy >=1.9.1
        - h5py
        - ligo-segments
        - lscsoft-glue >=1.54.1
        - matplotlib-base >=1.2.0
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-lalburst >={{ lalburst_version }}
        - python-lalinspiral >={{ lalinspiral_version }}
        - python-lalpulsar >={{ lalpulsar_version }}
        - python-ligo-lw
        - scipy >=0.9.0
      run:
        - astropy >=1.1.1
        - healpy >=1.9.1
        - h5py
        - {{ pin_subpackage('liblalinference', exact=True) }}
        - ligo-segments
        - lscsoft-glue >=1.54.1
        - matplotlib-base >=1.2.0
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalmetaio >={{ lalmetaio_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - python-lalburst >={{ lalburst_version }}
        - python-lalinspiral >={{ lalinspiral_version }}
        - python-lalpulsar >={{ lalpulsar_version }}
        - python-ligo-lw
        - scipy >=0.9.0
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        - python -m pytest -rs -v test/python/
      imports:
        - lalinference
        - lalinference.bayespputils
        - lalinference.imrtgr
        - lalinference.imrtgr.imrtgrutils
        - lalinference.imrtgr.nrutils
        - lalinference.imrtgr.pneqns
        - lalinference.lalinference_pipe_utils
        - lalinference.nest2pos
        - lalinference.plot
        - lalinference.tiger
        - lalinference.tiger.make_injtimes
        - lalinference.tiger.omegascans_dag
        - lalinference.tiger.postproc
        - lalinference.wrapper
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinference/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inference Library
      description: |
        The LSC Algorithm Inference Library for gravitational wave data
        analysis.  This package contains the python bindings.

  - name: lalinference
    script: install-bin.sh
    build:
      ignore_run_exports:
        - python
      # Prioritise nompi via build number
      number: {{ (build + 100) if (mpi or "nompi") == "nompi" else build }}
      string: {{ "nompi" if (mpi or "nompi") == "nompi" else ("mpi_" + mpi) }}_py{{ py }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man
        - llvm-openmp  # [osx]
        - make
      host:
        - gsl
        - {{ pin_subpackage('liblalinference', exact=True) }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - {{ mpi }}  # [mpi != 'nompi']
        - python
        - {{ pin_subpackage('python-lalinference', exact=True) }}
      run:
        - gsl
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalinference', exact=True) }}
        - liblalinspiral >={{ lalinspiral_version }}
        - llvm-openmp  # [osx]
        - {{ mpi }}  # [mpi != 'nompi']
        - python
        - {{ pin_subpackage('python-lalinference', exact=True) }}
    test:
      requires:
        - cpnest
        - openssh
      commands:
        # data files
        - test -f "${LALINFERENCE_DATADIR}/lalinference_pipe_example.ini"  # [unix]
        # C executables
        - lalinference_bench --psdlength 1000 --psdstart 1 --seglen 8 --srate 4096 --trigtime 0 --ifo H1 --H1-channel LALSimAdLIGO --H1-cache LALSimAdLIGO --dataseed 1324 --Niter 10 --fix-chirpmass 1.21
        #- lalinference_burst --help
        - lalinference_datadump --help
        - lalinference_injectedlike --help
        - lalinference_kombine --help
        - lalinference_mcmc --help
        - lalinference_nest --help
        - lalinference_version --verbose
        # python scripts
        - cbcBayesBurstPPAnalysis --help
        - cbcBayesBurstPostProc --help
        - cbcBayesCombinePTMCMCh5s --help
        - cbcBayesCombinePosteriors --help
        - cbcBayesCompPos --help
        - cbcBayesDIEvidence --help
        - cbcBayesGraceDBinfo --help
        - cbcBayesMCMC2pos --help
        - cbcBayesPPAnalysis --help
        - cbcBayesPlotSpinDisk --help
        - cbcBayesPosToSimBurst --help
        - cbcBayesPosToSimInspiral --help
        - cbcBayesPostProc --help
        - cbcBayesThermoInt --help
        - imrtgr_imr_consistency_test --help
        - lalinference_burst_pp_pipe --help
        - lalinference_coherence_test --help
        - lalinference_compute_roq_weights --help
        - lalinference_cpnest --help
        - lalinference_merge_posteriors --help
        - lalinference_multi_pipe --help
        - lalinference_nest2pos --help
        - lalinference_pipe --help
        - lalinference_pp_pipe --help
        - lalinference_review_test --help
      imports:
        - lalinference
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinference/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Inference Library
      description: |
        The LSC Algorithm Inference Library for gravitational wave data analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalinference/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Inference Library
  description: |
    The LSC Algorithm Inference Library for gravitational wave data analysis.

extra:
  feedstock-name: lalinference
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
    - vivienr
