# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rCiuSG3oUyLfGR/AZYQFR4YEwsrB1l9wTZ6RWF39yzjzc4CiGDHTN7w9ac9Q+j+lz5ftQWcmzXFUBYQin3uH+a0puIgKJadUM6mS8fRCslDy+Fc8Y+uBybyqObwRJxDMtclmifDtwFLGzsX6OKdef4ikicDFiE364T3chtR5okwbYfVVz8JeuGWSZklf1x+a8NgV20wbLXEf4iegWdcxlQT2ArM6Jc7koiqw0L4HsK9Xb87GQ9V/gH2r5+6V3QsEE9xUl7KKiz266E9csYNh7lgyZtNRpgyXNaHqO1btp01FvZGwI0iqzWwbom2/I2RZdYnUN/PpXt31v3uVib+O23GWeMwVKpWqPVo6EP+MTQ0miZOwXDyuJmFIWs7raBADp4WeIYpA359rCYo8ECknB8JttA7/mx0yyVH6erwNz7rIqqv3T1bvSUkeb0WLSjkPJD9O4EMToPMCrvlxg6/ph9cQ9rSjpPj0Ct6UBFn4l9S4oH4i8yoUC36p3LSMOACL7cZ9nUSkXIpnPd3WeIVYdSdYWnOS73gMIzNbehHCr42rcSJflXPSv5ffQ/zlX2oMjV6yJERMORdpTLA2CGy5gQgSgwsVnS6znZ/lC7YWc+Abv8N6nR/JhHPBRJemFQ0FDGYON08r91Cn8Ed+b4lLAesIvqEsrogtIwQ2OulO29Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
